// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: wallet/v1/wallet.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWalletServiceCreateAlipayRechargeOrder = "/wallet.v1.WalletService/CreateAlipayRechargeOrder"
const OperationWalletServiceCreateRechargeOrder = "/wallet.v1.WalletService/CreateRechargeOrder"
const OperationWalletServiceGetBalance = "/wallet.v1.WalletService/GetBalance"

type WalletServiceHTTPServer interface {
	CreateAlipayRechargeOrder(context.Context, *CreateAlipayRechargeOrderRequest) (*CreateRechargeOrderReply, error)
	CreateRechargeOrder(context.Context, *CreateRechargeOrderRequest) (*CreateRechargeOrderReply, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceReply, error)
}

func RegisterWalletServiceHTTPServer(s *http.Server, srv WalletServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/wallet/balance", _WalletService_GetBalance0_HTTP_Handler(srv))
	r.POST("/v1/wallet/recharges", _WalletService_CreateRechargeOrder0_HTTP_Handler(srv))
	r.POST("/v1/wallet/recharges/alipay", _WalletService_CreateAlipayRechargeOrder0_HTTP_Handler(srv))
}

func _WalletService_GetBalance0_HTTP_Handler(srv WalletServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBalanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWalletServiceGetBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBalance(ctx, req.(*GetBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBalanceReply)
		return ctx.Result(200, reply)
	}
}

func _WalletService_CreateRechargeOrder0_HTTP_Handler(srv WalletServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRechargeOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWalletServiceCreateRechargeOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRechargeOrder(ctx, req.(*CreateRechargeOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRechargeOrderReply)
		return ctx.Result(200, reply)
	}
}

func _WalletService_CreateAlipayRechargeOrder0_HTTP_Handler(srv WalletServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAlipayRechargeOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWalletServiceCreateAlipayRechargeOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAlipayRechargeOrder(ctx, req.(*CreateAlipayRechargeOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRechargeOrderReply)
		return ctx.Result(200, reply)
	}
}

type WalletServiceHTTPClient interface {
	CreateAlipayRechargeOrder(ctx context.Context, req *CreateAlipayRechargeOrderRequest, opts ...http.CallOption) (rsp *CreateRechargeOrderReply, err error)
	CreateRechargeOrder(ctx context.Context, req *CreateRechargeOrderRequest, opts ...http.CallOption) (rsp *CreateRechargeOrderReply, err error)
	GetBalance(ctx context.Context, req *GetBalanceRequest, opts ...http.CallOption) (rsp *GetBalanceReply, err error)
}

type WalletServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWalletServiceHTTPClient(client *http.Client) WalletServiceHTTPClient {
	return &WalletServiceHTTPClientImpl{client}
}

func (c *WalletServiceHTTPClientImpl) CreateAlipayRechargeOrder(ctx context.Context, in *CreateAlipayRechargeOrderRequest, opts ...http.CallOption) (*CreateRechargeOrderReply, error) {
	var out CreateRechargeOrderReply
	pattern := "/v1/wallet/recharges/alipay"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWalletServiceCreateAlipayRechargeOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WalletServiceHTTPClientImpl) CreateRechargeOrder(ctx context.Context, in *CreateRechargeOrderRequest, opts ...http.CallOption) (*CreateRechargeOrderReply, error) {
	var out CreateRechargeOrderReply
	pattern := "/v1/wallet/recharges"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWalletServiceCreateRechargeOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WalletServiceHTTPClientImpl) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...http.CallOption) (*GetBalanceReply, error) {
	var out GetBalanceReply
	pattern := "/v1/wallet/balance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWalletServiceGetBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
