// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: notify/v1/notify.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotifyServiceListMessages = "/notify.v1.NotifyService/ListMessages"
const OperationNotifyServicePushMessage = "/notify.v1.NotifyService/PushMessage"

type NotifyServiceHTTPServer interface {
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesReply, error)
	PushMessage(context.Context, *PushMessageRequest) (*PushMessageReply, error)
}

func RegisterNotifyServiceHTTPServer(s *http.Server, srv NotifyServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/notify/messages", _NotifyService_PushMessage0_HTTP_Handler(srv))
	r.GET("/v1/notify/messages", _NotifyService_ListMessages0_HTTP_Handler(srv))
}

func _NotifyService_PushMessage0_HTTP_Handler(srv NotifyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PushMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotifyServicePushMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PushMessage(ctx, req.(*PushMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PushMessageReply)
		return ctx.Result(200, reply)
	}
}

func _NotifyService_ListMessages0_HTTP_Handler(srv NotifyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotifyServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesReply)
		return ctx.Result(200, reply)
	}
}

type NotifyServiceHTTPClient interface {
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesReply, err error)
	PushMessage(ctx context.Context, req *PushMessageRequest, opts ...http.CallOption) (rsp *PushMessageReply, err error)
}

type NotifyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNotifyServiceHTTPClient(client *http.Client) NotifyServiceHTTPClient {
	return &NotifyServiceHTTPClientImpl{client}
}

func (c *NotifyServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesReply, error) {
	var out ListMessagesReply
	pattern := "/v1/notify/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotifyServiceListMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotifyServiceHTTPClientImpl) PushMessage(ctx context.Context, in *PushMessageRequest, opts ...http.CallOption) (*PushMessageReply, error) {
	var out PushMessageReply
	pattern := "/v1/notify/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotifyServicePushMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
