// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: order/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderServiceGetCurrentOrder = "/order.v1.OrderService/GetCurrentOrder"
const OperationOrderServiceGetOrderDetail = "/order.v1.OrderService/GetOrderDetail"
const OperationOrderServiceListOrders = "/order.v1.OrderService/ListOrders"
const OperationOrderServiceReportOrderException = "/order.v1.OrderService/ReportOrderException"

type OrderServiceHTTPServer interface {
	GetCurrentOrder(context.Context, *GetCurrentOrderRequest) (*GetCurrentOrderReply, error)
	GetOrderDetail(context.Context, *GetOrderDetailRequest) (*GetOrderDetailReply, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersReply, error)
	ReportOrderException(context.Context, *ReportOrderExceptionRequest) (*ReportOrderExceptionReply, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/orders/current", _OrderService_GetCurrentOrder0_HTTP_Handler(srv))
	r.GET("/v1/orders", _OrderService_ListOrders0_HTTP_Handler(srv))
	r.GET("/v1/orders/{rent_order_no}", _OrderService_GetOrderDetail0_HTTP_Handler(srv))
	r.POST("/v1/orders/{rent_order_no}:reportException", _OrderService_ReportOrderException0_HTTP_Handler(srv))
}

func _OrderService_GetCurrentOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetCurrentOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentOrder(ctx, req.(*GetCurrentOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurrentOrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ListOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrders(ctx, req.(*ListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetOrderDetail0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetOrderDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderDetail(ctx, req.(*GetOrderDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderDetailReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ReportOrderException0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReportOrderExceptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceReportOrderException)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportOrderException(ctx, req.(*ReportOrderExceptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReportOrderExceptionReply)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	GetCurrentOrder(ctx context.Context, req *GetCurrentOrderRequest, opts ...http.CallOption) (rsp *GetCurrentOrderReply, err error)
	GetOrderDetail(ctx context.Context, req *GetOrderDetailRequest, opts ...http.CallOption) (rsp *GetOrderDetailReply, err error)
	ListOrders(ctx context.Context, req *ListOrdersRequest, opts ...http.CallOption) (rsp *ListOrdersReply, err error)
	ReportOrderException(ctx context.Context, req *ReportOrderExceptionRequest, opts ...http.CallOption) (rsp *ReportOrderExceptionReply, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

func (c *OrderServiceHTTPClientImpl) GetCurrentOrder(ctx context.Context, in *GetCurrentOrderRequest, opts ...http.CallOption) (*GetCurrentOrderReply, error) {
	var out GetCurrentOrderReply
	pattern := "/v1/orders/current"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceGetCurrentOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...http.CallOption) (*GetOrderDetailReply, error) {
	var out GetOrderDetailReply
	pattern := "/v1/orders/{rent_order_no}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceGetOrderDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...http.CallOption) (*ListOrdersReply, error) {
	var out ListOrdersReply
	pattern := "/v1/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceListOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ReportOrderException(ctx context.Context, in *ReportOrderExceptionRequest, opts ...http.CallOption) (*ReportOrderExceptionReply, error) {
	var out ReportOrderExceptionReply
	pattern := "/v1/orders/{rent_order_no}:reportException"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceReportOrderException))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
