// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: deposit/v1/deposit.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DepositService_GetDepositStatus_FullMethodName      = "/deposit.v1.DepositService/GetDepositStatus"
	DepositService_CreateDepositOrder_FullMethodName    = "/deposit.v1.DepositService/CreateDepositOrder"
	DepositService_ApplyDepositExemption_FullMethodName = "/deposit.v1.DepositService/ApplyDepositExemption"
	DepositService_ListDepositRecords_FullMethodName    = "/deposit.v1.DepositService/ListDepositRecords"
)

// DepositServiceClient is the client API for DepositService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepositServiceClient interface {
	GetDepositStatus(ctx context.Context, in *GetDepositStatusRequest, opts ...grpc.CallOption) (*GetDepositStatusReply, error)
	CreateDepositOrder(ctx context.Context, in *CreateDepositOrderRequest, opts ...grpc.CallOption) (*CreateDepositOrderReply, error)
	ApplyDepositExemption(ctx context.Context, in *ApplyDepositExemptionRequest, opts ...grpc.CallOption) (*ApplyDepositExemptionReply, error)
	ListDepositRecords(ctx context.Context, in *ListDepositRecordsRequest, opts ...grpc.CallOption) (*ListDepositRecordsReply, error)
}

type depositServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositServiceClient(cc grpc.ClientConnInterface) DepositServiceClient {
	return &depositServiceClient{cc}
}

func (c *depositServiceClient) GetDepositStatus(ctx context.Context, in *GetDepositStatusRequest, opts ...grpc.CallOption) (*GetDepositStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositStatusReply)
	err := c.cc.Invoke(ctx, DepositService_GetDepositStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositServiceClient) CreateDepositOrder(ctx context.Context, in *CreateDepositOrderRequest, opts ...grpc.CallOption) (*CreateDepositOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDepositOrderReply)
	err := c.cc.Invoke(ctx, DepositService_CreateDepositOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositServiceClient) ApplyDepositExemption(ctx context.Context, in *ApplyDepositExemptionRequest, opts ...grpc.CallOption) (*ApplyDepositExemptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDepositExemptionReply)
	err := c.cc.Invoke(ctx, DepositService_ApplyDepositExemption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositServiceClient) ListDepositRecords(ctx context.Context, in *ListDepositRecordsRequest, opts ...grpc.CallOption) (*ListDepositRecordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDepositRecordsReply)
	err := c.cc.Invoke(ctx, DepositService_ListDepositRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositServiceServer is the server API for DepositService service.
// All implementations must embed UnimplementedDepositServiceServer
// for forward compatibility
type DepositServiceServer interface {
	GetDepositStatus(context.Context, *GetDepositStatusRequest) (*GetDepositStatusReply, error)
	CreateDepositOrder(context.Context, *CreateDepositOrderRequest) (*CreateDepositOrderReply, error)
	ApplyDepositExemption(context.Context, *ApplyDepositExemptionRequest) (*ApplyDepositExemptionReply, error)
	ListDepositRecords(context.Context, *ListDepositRecordsRequest) (*ListDepositRecordsReply, error)
	mustEmbedUnimplementedDepositServiceServer()
}

// UnimplementedDepositServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDepositServiceServer struct {
}

func (UnimplementedDepositServiceServer) GetDepositStatus(context.Context, *GetDepositStatusRequest) (*GetDepositStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositStatus not implemented")
}
func (UnimplementedDepositServiceServer) CreateDepositOrder(context.Context, *CreateDepositOrderRequest) (*CreateDepositOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDepositOrder not implemented")
}
func (UnimplementedDepositServiceServer) ApplyDepositExemption(context.Context, *ApplyDepositExemptionRequest) (*ApplyDepositExemptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDepositExemption not implemented")
}
func (UnimplementedDepositServiceServer) ListDepositRecords(context.Context, *ListDepositRecordsRequest) (*ListDepositRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDepositRecords not implemented")
}
func (UnimplementedDepositServiceServer) mustEmbedUnimplementedDepositServiceServer() {}

// UnsafeDepositServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositServiceServer will
// result in compilation errors.
type UnsafeDepositServiceServer interface {
	mustEmbedUnimplementedDepositServiceServer()
}

func RegisterDepositServiceServer(s grpc.ServiceRegistrar, srv DepositServiceServer) {
	s.RegisterService(&DepositService_ServiceDesc, srv)
}

func _DepositService_GetDepositStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).GetDepositStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_GetDepositStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).GetDepositStatus(ctx, req.(*GetDepositStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositService_CreateDepositOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepositOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).CreateDepositOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_CreateDepositOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).CreateDepositOrder(ctx, req.(*CreateDepositOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositService_ApplyDepositExemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDepositExemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).ApplyDepositExemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_ApplyDepositExemption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).ApplyDepositExemption(ctx, req.(*ApplyDepositExemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositService_ListDepositRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDepositRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).ListDepositRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_ListDepositRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).ListDepositRecords(ctx, req.(*ListDepositRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepositService_ServiceDesc is the grpc.ServiceDesc for DepositService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepositService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deposit.v1.DepositService",
	HandlerType: (*DepositServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepositStatus",
			Handler:    _DepositService_GetDepositStatus_Handler,
		},
		{
			MethodName: "CreateDepositOrder",
			Handler:    _DepositService_CreateDepositOrder_Handler,
		},
		{
			MethodName: "ApplyDepositExemption",
			Handler:    _DepositService_ApplyDepositExemption_Handler,
		},
		{
			MethodName: "ListDepositRecords",
			Handler:    _DepositService_ListDepositRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deposit/v1/deposit.proto",
}
