// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: deposit/v1/deposit.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDepositServiceApplyDepositExemption = "/deposit.v1.DepositService/ApplyDepositExemption"
const OperationDepositServiceCreateDepositOrder = "/deposit.v1.DepositService/CreateDepositOrder"
const OperationDepositServiceGetDepositStatus = "/deposit.v1.DepositService/GetDepositStatus"
const OperationDepositServiceListDepositRecords = "/deposit.v1.DepositService/ListDepositRecords"

type DepositServiceHTTPServer interface {
	ApplyDepositExemption(context.Context, *ApplyDepositExemptionRequest) (*ApplyDepositExemptionReply, error)
	CreateDepositOrder(context.Context, *CreateDepositOrderRequest) (*CreateDepositOrderReply, error)
	GetDepositStatus(context.Context, *GetDepositStatusRequest) (*GetDepositStatusReply, error)
	ListDepositRecords(context.Context, *ListDepositRecordsRequest) (*ListDepositRecordsReply, error)
}

func RegisterDepositServiceHTTPServer(s *http.Server, srv DepositServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/deposits/status", _DepositService_GetDepositStatus0_HTTP_Handler(srv))
	r.POST("/v1/deposits/orders", _DepositService_CreateDepositOrder0_HTTP_Handler(srv))
	r.POST("/v1/deposits/exemptions:apply", _DepositService_ApplyDepositExemption0_HTTP_Handler(srv))
	r.GET("/v1/deposits/records", _DepositService_ListDepositRecords0_HTTP_Handler(srv))
}

func _DepositService_GetDepositStatus0_HTTP_Handler(srv DepositServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDepositStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositServiceGetDepositStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDepositStatus(ctx, req.(*GetDepositStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDepositStatusReply)
		return ctx.Result(200, reply)
	}
}

func _DepositService_CreateDepositOrder0_HTTP_Handler(srv DepositServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDepositOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositServiceCreateDepositOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDepositOrder(ctx, req.(*CreateDepositOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDepositOrderReply)
		return ctx.Result(200, reply)
	}
}

func _DepositService_ApplyDepositExemption0_HTTP_Handler(srv DepositServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyDepositExemptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositServiceApplyDepositExemption)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyDepositExemption(ctx, req.(*ApplyDepositExemptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplyDepositExemptionReply)
		return ctx.Result(200, reply)
	}
}

func _DepositService_ListDepositRecords0_HTTP_Handler(srv DepositServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDepositRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositServiceListDepositRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDepositRecords(ctx, req.(*ListDepositRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDepositRecordsReply)
		return ctx.Result(200, reply)
	}
}

type DepositServiceHTTPClient interface {
	ApplyDepositExemption(ctx context.Context, req *ApplyDepositExemptionRequest, opts ...http.CallOption) (rsp *ApplyDepositExemptionReply, err error)
	CreateDepositOrder(ctx context.Context, req *CreateDepositOrderRequest, opts ...http.CallOption) (rsp *CreateDepositOrderReply, err error)
	GetDepositStatus(ctx context.Context, req *GetDepositStatusRequest, opts ...http.CallOption) (rsp *GetDepositStatusReply, err error)
	ListDepositRecords(ctx context.Context, req *ListDepositRecordsRequest, opts ...http.CallOption) (rsp *ListDepositRecordsReply, err error)
}

type DepositServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDepositServiceHTTPClient(client *http.Client) DepositServiceHTTPClient {
	return &DepositServiceHTTPClientImpl{client}
}

func (c *DepositServiceHTTPClientImpl) ApplyDepositExemption(ctx context.Context, in *ApplyDepositExemptionRequest, opts ...http.CallOption) (*ApplyDepositExemptionReply, error) {
	var out ApplyDepositExemptionReply
	pattern := "/v1/deposits/exemptions:apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepositServiceApplyDepositExemption))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepositServiceHTTPClientImpl) CreateDepositOrder(ctx context.Context, in *CreateDepositOrderRequest, opts ...http.CallOption) (*CreateDepositOrderReply, error) {
	var out CreateDepositOrderReply
	pattern := "/v1/deposits/orders"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepositServiceCreateDepositOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepositServiceHTTPClientImpl) GetDepositStatus(ctx context.Context, in *GetDepositStatusRequest, opts ...http.CallOption) (*GetDepositStatusReply, error) {
	var out GetDepositStatusReply
	pattern := "/v1/deposits/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepositServiceGetDepositStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepositServiceHTTPClientImpl) ListDepositRecords(ctx context.Context, in *ListDepositRecordsRequest, opts ...http.CallOption) (*ListDepositRecordsReply, error) {
	var out ListDepositRecordsReply
	pattern := "/v1/deposits/records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepositServiceListDepositRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
