// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: charger/v1/charger.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChargerServiceNotifyBorrowResult = "/charger.v1.ChargerService/NotifyBorrowResult"
const OperationChargerServiceNotifyReturnResult = "/charger.v1.ChargerService/NotifyReturnResult"
const OperationChargerServiceScanBorrow = "/charger.v1.ChargerService/ScanBorrow"

type ChargerServiceHTTPServer interface {
	NotifyBorrowResult(context.Context, *NotifyBorrowResultRequest) (*NotifyBorrowResultReply, error)
	NotifyReturnResult(context.Context, *NotifyReturnResultRequest) (*NotifyReturnResultReply, error)
	ScanBorrow(context.Context, *ScanBorrowRequest) (*ScanBorrowReply, error)
}

func RegisterChargerServiceHTTPServer(s *http.Server, srv ChargerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/chargers/scan:borrow", _ChargerService_ScanBorrow0_HTTP_Handler(srv))
	r.POST("/v1/internal/chargers/borrow:notify", _ChargerService_NotifyBorrowResult0_HTTP_Handler(srv))
	r.POST("/v1/internal/chargers/return:notify", _ChargerService_NotifyReturnResult0_HTTP_Handler(srv))
}

func _ChargerService_ScanBorrow0_HTTP_Handler(srv ChargerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScanBorrowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChargerServiceScanBorrow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ScanBorrow(ctx, req.(*ScanBorrowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScanBorrowReply)
		return ctx.Result(200, reply)
	}
}

func _ChargerService_NotifyBorrowResult0_HTTP_Handler(srv ChargerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in NotifyBorrowResultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChargerServiceNotifyBorrowResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.NotifyBorrowResult(ctx, req.(*NotifyBorrowResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotifyBorrowResultReply)
		return ctx.Result(200, reply)
	}
}

func _ChargerService_NotifyReturnResult0_HTTP_Handler(srv ChargerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in NotifyReturnResultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChargerServiceNotifyReturnResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.NotifyReturnResult(ctx, req.(*NotifyReturnResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotifyReturnResultReply)
		return ctx.Result(200, reply)
	}
}

type ChargerServiceHTTPClient interface {
	NotifyBorrowResult(ctx context.Context, req *NotifyBorrowResultRequest, opts ...http.CallOption) (rsp *NotifyBorrowResultReply, err error)
	NotifyReturnResult(ctx context.Context, req *NotifyReturnResultRequest, opts ...http.CallOption) (rsp *NotifyReturnResultReply, err error)
	ScanBorrow(ctx context.Context, req *ScanBorrowRequest, opts ...http.CallOption) (rsp *ScanBorrowReply, err error)
}

type ChargerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewChargerServiceHTTPClient(client *http.Client) ChargerServiceHTTPClient {
	return &ChargerServiceHTTPClientImpl{client}
}

func (c *ChargerServiceHTTPClientImpl) NotifyBorrowResult(ctx context.Context, in *NotifyBorrowResultRequest, opts ...http.CallOption) (*NotifyBorrowResultReply, error) {
	var out NotifyBorrowResultReply
	pattern := "/v1/internal/chargers/borrow:notify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChargerServiceNotifyBorrowResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChargerServiceHTTPClientImpl) NotifyReturnResult(ctx context.Context, in *NotifyReturnResultRequest, opts ...http.CallOption) (*NotifyReturnResultReply, error) {
	var out NotifyReturnResultReply
	pattern := "/v1/internal/chargers/return:notify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChargerServiceNotifyReturnResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChargerServiceHTTPClientImpl) ScanBorrow(ctx context.Context, in *ScanBorrowRequest, opts ...http.CallOption) (*ScanBorrowReply, error) {
	var out ScanBorrowReply
	pattern := "/v1/chargers/scan:borrow"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChargerServiceScanBorrow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
