// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: charger/v1/charger.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ChargerService_ScanBorrow_FullMethodName         = "/charger.v1.ChargerService/ScanBorrow"
	ChargerService_NotifyBorrowResult_FullMethodName = "/charger.v1.ChargerService/NotifyBorrowResult"
	ChargerService_NotifyReturnResult_FullMethodName = "/charger.v1.ChargerService/NotifyReturnResult"
)

// ChargerServiceClient is the client API for ChargerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChargerServiceClient interface {
	ScanBorrow(ctx context.Context, in *ScanBorrowRequest, opts ...grpc.CallOption) (*ScanBorrowReply, error)
	NotifyBorrowResult(ctx context.Context, in *NotifyBorrowResultRequest, opts ...grpc.CallOption) (*NotifyBorrowResultReply, error)
	NotifyReturnResult(ctx context.Context, in *NotifyReturnResultRequest, opts ...grpc.CallOption) (*NotifyReturnResultReply, error)
}

type chargerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChargerServiceClient(cc grpc.ClientConnInterface) ChargerServiceClient {
	return &chargerServiceClient{cc}
}

func (c *chargerServiceClient) ScanBorrow(ctx context.Context, in *ScanBorrowRequest, opts ...grpc.CallOption) (*ScanBorrowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanBorrowReply)
	err := c.cc.Invoke(ctx, ChargerService_ScanBorrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chargerServiceClient) NotifyBorrowResult(ctx context.Context, in *NotifyBorrowResultRequest, opts ...grpc.CallOption) (*NotifyBorrowResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyBorrowResultReply)
	err := c.cc.Invoke(ctx, ChargerService_NotifyBorrowResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chargerServiceClient) NotifyReturnResult(ctx context.Context, in *NotifyReturnResultRequest, opts ...grpc.CallOption) (*NotifyReturnResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyReturnResultReply)
	err := c.cc.Invoke(ctx, ChargerService_NotifyReturnResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChargerServiceServer is the server API for ChargerService service.
// All implementations must embed UnimplementedChargerServiceServer
// for forward compatibility
type ChargerServiceServer interface {
	ScanBorrow(context.Context, *ScanBorrowRequest) (*ScanBorrowReply, error)
	NotifyBorrowResult(context.Context, *NotifyBorrowResultRequest) (*NotifyBorrowResultReply, error)
	NotifyReturnResult(context.Context, *NotifyReturnResultRequest) (*NotifyReturnResultReply, error)
	mustEmbedUnimplementedChargerServiceServer()
}

// UnimplementedChargerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChargerServiceServer struct {
}

func (UnimplementedChargerServiceServer) ScanBorrow(context.Context, *ScanBorrowRequest) (*ScanBorrowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanBorrow not implemented")
}
func (UnimplementedChargerServiceServer) NotifyBorrowResult(context.Context, *NotifyBorrowResultRequest) (*NotifyBorrowResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyBorrowResult not implemented")
}
func (UnimplementedChargerServiceServer) NotifyReturnResult(context.Context, *NotifyReturnResultRequest) (*NotifyReturnResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyReturnResult not implemented")
}
func (UnimplementedChargerServiceServer) mustEmbedUnimplementedChargerServiceServer() {}

// UnsafeChargerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChargerServiceServer will
// result in compilation errors.
type UnsafeChargerServiceServer interface {
	mustEmbedUnimplementedChargerServiceServer()
}

func RegisterChargerServiceServer(s grpc.ServiceRegistrar, srv ChargerServiceServer) {
	s.RegisterService(&ChargerService_ServiceDesc, srv)
}

func _ChargerService_ScanBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanBorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargerServiceServer).ScanBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChargerService_ScanBorrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargerServiceServer).ScanBorrow(ctx, req.(*ScanBorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChargerService_NotifyBorrowResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyBorrowResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargerServiceServer).NotifyBorrowResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChargerService_NotifyBorrowResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargerServiceServer).NotifyBorrowResult(ctx, req.(*NotifyBorrowResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChargerService_NotifyReturnResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyReturnResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargerServiceServer).NotifyReturnResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChargerService_NotifyReturnResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargerServiceServer).NotifyReturnResult(ctx, req.(*NotifyReturnResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChargerService_ServiceDesc is the grpc.ServiceDesc for ChargerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChargerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charger.v1.ChargerService",
	HandlerType: (*ChargerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanBorrow",
			Handler:    _ChargerService_ScanBorrow_Handler,
		},
		{
			MethodName: "NotifyBorrowResult",
			Handler:    _ChargerService_NotifyBorrowResult_Handler,
		},
		{
			MethodName: "NotifyReturnResult",
			Handler:    _ChargerService_NotifyReturnResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "charger/v1/charger.proto",
}
