// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: payment/v1/payment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PaymentService_CreateWxPayOrder_FullMethodName = "/payment.v1.PaymentService/CreateWxPayOrder"
	PaymentService_QueryPayOrder_FullMethodName    = "/payment.v1.PaymentService/QueryPayOrder"
	PaymentService_WxPayNotify_FullMethodName      = "/payment.v1.PaymentService/WxPayNotify"
	PaymentService_AlipayNotify_FullMethodName     = "/payment.v1.PaymentService/AlipayNotify"
	PaymentService_AlipayHeartbeat_FullMethodName  = "/payment.v1.PaymentService/AlipayHeartbeat"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreateWxPayOrder(ctx context.Context, in *CreateWxPayOrderRequest, opts ...grpc.CallOption) (*CreateWxPayOrderReply, error)
	QueryPayOrder(ctx context.Context, in *QueryPayOrderRequest, opts ...grpc.CallOption) (*QueryPayOrderReply, error)
	WxPayNotify(ctx context.Context, in *WxPayNotifyRequest, opts ...grpc.CallOption) (*WxPayNotifyReply, error)
	AlipayNotify(ctx context.Context, in *AlipayNotifyRequest, opts ...grpc.CallOption) (*AlipayNotifyReply, error)
	AlipayHeartbeat(ctx context.Context, in *AlipayHeartbeatRequest, opts ...grpc.CallOption) (*AlipayHeartbeatReply, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateWxPayOrder(ctx context.Context, in *CreateWxPayOrderRequest, opts ...grpc.CallOption) (*CreateWxPayOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWxPayOrderReply)
	err := c.cc.Invoke(ctx, PaymentService_CreateWxPayOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) QueryPayOrder(ctx context.Context, in *QueryPayOrderRequest, opts ...grpc.CallOption) (*QueryPayOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPayOrderReply)
	err := c.cc.Invoke(ctx, PaymentService_QueryPayOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) WxPayNotify(ctx context.Context, in *WxPayNotifyRequest, opts ...grpc.CallOption) (*WxPayNotifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WxPayNotifyReply)
	err := c.cc.Invoke(ctx, PaymentService_WxPayNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AlipayNotify(ctx context.Context, in *AlipayNotifyRequest, opts ...grpc.CallOption) (*AlipayNotifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlipayNotifyReply)
	err := c.cc.Invoke(ctx, PaymentService_AlipayNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AlipayHeartbeat(ctx context.Context, in *AlipayHeartbeatRequest, opts ...grpc.CallOption) (*AlipayHeartbeatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlipayHeartbeatReply)
	err := c.cc.Invoke(ctx, PaymentService_AlipayHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	CreateWxPayOrder(context.Context, *CreateWxPayOrderRequest) (*CreateWxPayOrderReply, error)
	QueryPayOrder(context.Context, *QueryPayOrderRequest) (*QueryPayOrderReply, error)
	WxPayNotify(context.Context, *WxPayNotifyRequest) (*WxPayNotifyReply, error)
	AlipayNotify(context.Context, *AlipayNotifyRequest) (*AlipayNotifyReply, error)
	AlipayHeartbeat(context.Context, *AlipayHeartbeatRequest) (*AlipayHeartbeatReply, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) CreateWxPayOrder(context.Context, *CreateWxPayOrderRequest) (*CreateWxPayOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWxPayOrder not implemented")
}
func (UnimplementedPaymentServiceServer) QueryPayOrder(context.Context, *QueryPayOrderRequest) (*QueryPayOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPayOrder not implemented")
}
func (UnimplementedPaymentServiceServer) WxPayNotify(context.Context, *WxPayNotifyRequest) (*WxPayNotifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WxPayNotify not implemented")
}
func (UnimplementedPaymentServiceServer) AlipayNotify(context.Context, *AlipayNotifyRequest) (*AlipayNotifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayNotify not implemented")
}
func (UnimplementedPaymentServiceServer) AlipayHeartbeat(context.Context, *AlipayHeartbeatRequest) (*AlipayHeartbeatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayHeartbeat not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateWxPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWxPayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateWxPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateWxPayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateWxPayOrder(ctx, req.(*CreateWxPayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_QueryPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).QueryPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_QueryPayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).QueryPayOrder(ctx, req.(*QueryPayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_WxPayNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WxPayNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).WxPayNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_WxPayNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).WxPayNotify(ctx, req.(*WxPayNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AlipayNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AlipayNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AlipayNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AlipayNotify(ctx, req.(*AlipayNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AlipayHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AlipayHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AlipayHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AlipayHeartbeat(ctx, req.(*AlipayHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWxPayOrder",
			Handler:    _PaymentService_CreateWxPayOrder_Handler,
		},
		{
			MethodName: "QueryPayOrder",
			Handler:    _PaymentService_QueryPayOrder_Handler,
		},
		{
			MethodName: "WxPayNotify",
			Handler:    _PaymentService_WxPayNotify_Handler,
		},
		{
			MethodName: "AlipayNotify",
			Handler:    _PaymentService_AlipayNotify_Handler,
		},
		{
			MethodName: "AlipayHeartbeat",
			Handler:    _PaymentService_AlipayHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
