// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: payment/v1/payment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPaymentServiceAlipayHeartbeat = "/payment.v1.PaymentService/AlipayHeartbeat"
const OperationPaymentServiceAlipayNotify = "/payment.v1.PaymentService/AlipayNotify"
const OperationPaymentServiceCreateWxPayOrder = "/payment.v1.PaymentService/CreateWxPayOrder"
const OperationPaymentServiceQueryPayOrder = "/payment.v1.PaymentService/QueryPayOrder"
const OperationPaymentServiceWxPayNotify = "/payment.v1.PaymentService/WxPayNotify"

type PaymentServiceHTTPServer interface {
	AlipayHeartbeat(context.Context, *AlipayHeartbeatRequest) (*AlipayHeartbeatReply, error)
	AlipayNotify(context.Context, *AlipayNotifyRequest) (*AlipayNotifyReply, error)
	CreateWxPayOrder(context.Context, *CreateWxPayOrderRequest) (*CreateWxPayOrderReply, error)
	QueryPayOrder(context.Context, *QueryPayOrderRequest) (*QueryPayOrderReply, error)
	WxPayNotify(context.Context, *WxPayNotifyRequest) (*WxPayNotifyReply, error)
}

func RegisterPaymentServiceHTTPServer(s *http.Server, srv PaymentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/payments/wx/orders", _PaymentService_CreateWxPayOrder0_HTTP_Handler(srv))
	r.GET("/v1/payments/orders/{out_trade_no}", _PaymentService_QueryPayOrder0_HTTP_Handler(srv))
	r.POST("/v1/payments/wx/notify", _PaymentService_WxPayNotify0_HTTP_Handler(srv))
	r.POST("/v1/payments/alipay/notify", _PaymentService_AlipayNotify0_HTTP_Handler(srv))
	r.GET("/v1/payments/alipay/heartbeat", _PaymentService_AlipayHeartbeat0_HTTP_Handler(srv))
}

func _PaymentService_CreateWxPayOrder0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWxPayOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceCreateWxPayOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWxPayOrder(ctx, req.(*CreateWxPayOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWxPayOrderReply)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_QueryPayOrder0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryPayOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceQueryPayOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryPayOrder(ctx, req.(*QueryPayOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryPayOrderReply)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_WxPayNotify0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WxPayNotifyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceWxPayNotify)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WxPayNotify(ctx, req.(*WxPayNotifyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WxPayNotifyReply)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_AlipayNotify0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AlipayNotifyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceAlipayNotify)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AlipayNotify(ctx, req.(*AlipayNotifyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlipayNotifyReply)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_AlipayHeartbeat0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AlipayHeartbeatRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceAlipayHeartbeat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AlipayHeartbeat(ctx, req.(*AlipayHeartbeatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlipayHeartbeatReply)
		return ctx.Result(200, reply)
	}
}

type PaymentServiceHTTPClient interface {
	AlipayHeartbeat(ctx context.Context, req *AlipayHeartbeatRequest, opts ...http.CallOption) (rsp *AlipayHeartbeatReply, err error)
	AlipayNotify(ctx context.Context, req *AlipayNotifyRequest, opts ...http.CallOption) (rsp *AlipayNotifyReply, err error)
	CreateWxPayOrder(ctx context.Context, req *CreateWxPayOrderRequest, opts ...http.CallOption) (rsp *CreateWxPayOrderReply, err error)
	QueryPayOrder(ctx context.Context, req *QueryPayOrderRequest, opts ...http.CallOption) (rsp *QueryPayOrderReply, err error)
	WxPayNotify(ctx context.Context, req *WxPayNotifyRequest, opts ...http.CallOption) (rsp *WxPayNotifyReply, err error)
}

type PaymentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPaymentServiceHTTPClient(client *http.Client) PaymentServiceHTTPClient {
	return &PaymentServiceHTTPClientImpl{client}
}

func (c *PaymentServiceHTTPClientImpl) AlipayHeartbeat(ctx context.Context, in *AlipayHeartbeatRequest, opts ...http.CallOption) (*AlipayHeartbeatReply, error) {
	var out AlipayHeartbeatReply
	pattern := "/v1/payments/alipay/heartbeat"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentServiceAlipayHeartbeat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) AlipayNotify(ctx context.Context, in *AlipayNotifyRequest, opts ...http.CallOption) (*AlipayNotifyReply, error) {
	var out AlipayNotifyReply
	pattern := "/v1/payments/alipay/notify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceAlipayNotify))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) CreateWxPayOrder(ctx context.Context, in *CreateWxPayOrderRequest, opts ...http.CallOption) (*CreateWxPayOrderReply, error) {
	var out CreateWxPayOrderReply
	pattern := "/v1/payments/wx/orders"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceCreateWxPayOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) QueryPayOrder(ctx context.Context, in *QueryPayOrderRequest, opts ...http.CallOption) (*QueryPayOrderReply, error) {
	var out QueryPayOrderReply
	pattern := "/v1/payments/orders/{out_trade_no}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentServiceQueryPayOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) WxPayNotify(ctx context.Context, in *WxPayNotifyRequest, opts ...http.CallOption) (*WxPayNotifyReply, error) {
	var out WxPayNotifyReply
	pattern := "/v1/payments/wx/notify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceWxPayNotify))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
