CREATE TABLE IF NOT EXISTS `stations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `station_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1=ONLINE,2=OFFLINE',
  `pricing_rule_id` VARCHAR(64) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stations_station_id` (`station_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `pricing_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rule_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `free_minutes` INT NOT NULL DEFAULT 0,
  `unit_minutes` INT NOT NULL DEFAULT 30,
  `unit_price` BIGINT NOT NULL DEFAULT 100,
  `daily_cap` BIGINT NOT NULL DEFAULT 2999,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pricing_rules_rule_id` (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `powerbanks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `powerbank_id` VARCHAR(64) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1=IN_STATION,2=BORROWED,3=DISABLED',
  `current_station_id` VARCHAR(64) NOT NULL DEFAULT '',
  `current_slot_id` VARCHAR(64) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_powerbanks_powerbank_id` (`powerbank_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `station_slots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slot_id` VARCHAR(64) NOT NULL,
  `station_id` VARCHAR(64) NOT NULL,
  `powerbank_id` VARCHAR(64) NOT NULL DEFAULT '',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1=IDLE,2=RESERVED,3=EMPTY,4=FAULT',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_station_slots_slot_id` (`slot_id`),
  KEY `idx_station_slots_station_status` (`station_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
