// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: support/v1/support.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSupportServiceListSessionTurns = "/support.v1.SupportService/ListSessionTurns"
const OperationSupportServiceSendMessage = "/support.v1.SupportService/SendMessage"

type SupportServiceHTTPServer interface {
	ListSessionTurns(context.Context, *ListSessionTurnsRequest) (*ListSessionTurnsReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
}

func RegisterSupportServiceHTTPServer(s *http.Server, srv SupportServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/support/chat:send", _SupportService_SendMessage0_HTTP_Handler(srv))
	r.GET("/v1/support/sessions/{session_id}/turns", _SupportService_ListSessionTurns0_HTTP_Handler(srv))
}

func _SupportService_SendMessage0_HTTP_Handler(srv SupportServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSupportServiceSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _SupportService_ListSessionTurns0_HTTP_Handler(srv SupportServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionTurnsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSupportServiceListSessionTurns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessionTurns(ctx, req.(*ListSessionTurnsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionTurnsReply)
		return ctx.Result(200, reply)
	}
}

type SupportServiceHTTPClient interface {
	ListSessionTurns(ctx context.Context, req *ListSessionTurnsRequest, opts ...http.CallOption) (rsp *ListSessionTurnsReply, err error)
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
}

type SupportServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSupportServiceHTTPClient(client *http.Client) SupportServiceHTTPClient {
	return &SupportServiceHTTPClientImpl{client}
}

func (c *SupportServiceHTTPClientImpl) ListSessionTurns(ctx context.Context, in *ListSessionTurnsRequest, opts ...http.CallOption) (*ListSessionTurnsReply, error) {
	var out ListSessionTurnsReply
	pattern := "/v1/support/sessions/{session_id}/turns"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSupportServiceListSessionTurns))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SupportServiceHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/v1/support/chat:send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSupportServiceSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
