// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/biz"
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/data"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, payment *conf.Payment, ai *conf.AI, credit *conf.Credit, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, jwt, logger)
	userService := service.NewUserService(userUsecase, authUsecase)
	paymentRepo := data.NewPaymentRepo(dataData, logger)
	wxPayGateway := data.NewWxPayGateway(payment, logger)
	alipayGateway := data.NewAlipayGateway(payment, logger)
	notifyRepo := data.NewNotifyRepo(dataData, logger)
	notifier := data.NewMQTTNotifier(dataData, logger)
	notifyUsecase := biz.NewNotifyUsecase(notifyRepo, notifier, logger)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, wxPayGateway, alipayGateway, notifyUsecase, logger)
	paymentService := service.NewPaymentService(paymentUsecase)
	walletRepo := data.NewWalletRepo(dataData, logger)
	walletUsecase := biz.NewWalletUsecase(paymentRepo, walletRepo, wxPayGateway, alipayGateway, logger)
	walletService := service.NewWalletService(walletUsecase)
	notifyService := service.NewNotifyService(notifyUsecase)
	depositRepo := data.NewDepositRepo(dataData, logger)
	creditGateway := data.NewCreditGateway(credit, logger)
	depositUsecase := biz.NewDepositUsecase(depositRepo, paymentRepo, wxPayGateway, alipayGateway, creditGateway, logger)
	depositService := service.NewDepositService(depositUsecase)
	chargerRepo := data.NewChargerRepo(dataData, logger)
	chargerUsecase := biz.NewChargerUsecase(chargerRepo, depositUsecase, notifyUsecase, logger)
	chargerService := service.NewChargerService(chargerUsecase)
	orderRepo := data.NewOrderRepo(dataData, logger)
	orderUsecase := biz.NewOrderUsecase(orderRepo, logger)
	orderService := service.NewOrderService(orderUsecase)
	supportRepo := data.NewSupportRepo(dataData, logger)
	modelChatGateway := data.NewOpenAIChatClient(ai, logger)
	supportUsecase := biz.NewSupportUsecase(supportRepo, modelChatGateway, userUsecase, walletUsecase, depositUsecase, orderUsecase, logger)
	supportService := service.NewSupportService(supportUsecase)
	grpcServer := server.NewGRPCServer(confServer, jwt, greeterService, userService, paymentService, walletService, notifyService, depositService, chargerService, orderService, supportService, logger)
	authService := service.NewAuthService(authUsecase)
	httpServer := server.NewHTTPServer(confServer, jwt, greeterService, authService, userService, paymentService, walletService, notifyService, depositService, chargerService, orderService, supportService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
